- experiments/Cargo.lock
- experiments/Cargo.toml
- experiments/src/error.rs
- experiments/src/evaluator.rs
- experiments/src/http_client.rs
- experiments/src/lib.rs
- experiments/src/matcher.rs
- experiments/src/persistence.rs
> Adds basic crate structure

- experiments/Cargo.lock
- experiments/Cargo.toml
- experiments/src/error.rs
- experiments/src/persistence.rs
Uses `rkv` for persistence. 
This uses `rkv`'s `lmdb` backend, which is [unstable](https://github.com/mozilla/rkv), I'll change it to `SafeMode` on a follow-up based on the feedback I get here.
> Adds basic persistence.

- experiments/Cargo.lock
- experiments/Cargo.toml
- experiments/examples/experiment.rs
- experiments/src/config.rs
- experiments/src/lib.rs
- experiments/src/uuid.rs
Adds some config parameters that can be passed in for debugging
> Adds custom config for initializing experiments

- experiments/Cargo.lock
- experiments/Cargo.toml
- experiments/examples/README.md
- experiments/examples/config/config.json
- experiments/examples/config/rapid-release-control.json
- experiments/examples/config/rapid-rutabagas-treatment.json
- experiments/examples/experiment.rs
- experiments/src/evaluator.rs
- experiments/src/lib.rs
Adds a command-line interface to interact with the Nimbus SDK.
You can check out the [README.md](https://github.com/mozilla/nimbus-sdk/blob/example-cli/experiments/examples/README.md) for a quick `How to use`
> Adds a cli demo to interact with experiments

- .circleci/config.yml
Ooops, forgot to update the CircleCI config...   will use my Admin powers to go ahead and merge this.
> Fix CI after changing directory name

- nimbus/examples/experiment.rs
Sorry to keep cowboy'ing this, I promise this is the last one :)
> Fix example after renaming to NimbusClient

- nimbus/src/http_client.rs
- nimbus/src/sampling.rs
We should try and get this happening automatically in circle, but for now...
> Keep clippy happy

- android/.buildconfig.yaml
- nimbus/Cargo.lock
- nimbus/uniffi.toml
Add uniffi.toml with package name
> Update uniffi in order to set package name

- nimbus/Cargo.lock
- nimbus/Cargo.toml
- nimbus/src/lib.rs
Fixes https://jira.mozilla.com/browse/NIBSSD-71.
This change makes the DB initialize lazily.
> Avoid I/O in constructor

- nimbus/Cargo.toml
Related to https://jira.mozilla.com/browse/NIBSSD-85 I noticed there's a dependency that's not actually used.
> Remove unused chrono dependency

- nimbus/Cargo.lock
> Update Cargo.lock to reflect the removal of chrono dep in #43

- nimbus/src/enrollment.rs
When I megazord this into appservices, our clippy lints want to run on nimbus as well, and the simplest way to deal with that seems to be fixing them here.
> Fix clippy lints

- .circleci/config.yml
- nimbus/Cargo.toml
- nimbus/src/enrollment.rs
- nimbus/src/lib.rs
- nimbus/src/persistence.rs
- nimbus/tests/test_fs_client.rs
There's a bit of duplication here that isn't ideal, but I think this is fairly reasonable - happy to play with other approaches though.
> Implement transactions and the choice of the rkv back-end via features.

- .circleci/config.yml
- codecov.yml
- nimbus/Cargo.toml
- nimbus/build.rs
- nimbus/src/lib.rs
The first commit shaves off 1m30 out of a 7m30 job, the coverage isn't perfect but it's better than nothing :)
> Add code coverage generation

- CHANGELOG.md
- README.md
- nimbus/Cargo.lock
- nimbus/Cargo.toml
- nimbus/src/enrollment.rs
I tried making this with `cargo release` and it seemed pretty nice, so I've added some instructions to that effect as well.
> Release v0.6.3

- nimbus/src/lib.rs
- nimbus/src/nimbus.idl
For https://jira.mozilla.com/browse/SDK-101
> Add `get_experiment_branches` method

- nimbus/Cargo.lock
- nimbus/Cargo.toml
- nimbus/examples/experiment.rs
- nimbus/src/client/fs_client.rs
- nimbus/src/client/http_client.rs
- nimbus/src/client/mod.rs
- nimbus/src/client/null_client.rs
- nimbus/src/dbcache.rs
- nimbus/src/error.rs
- nimbus/src/lib.rs
- nimbus/src/nimbus.idl
- nimbus/tests/common/mod.rs
- nimbus/tests/test_fs_client.rs
- nimbus/tests/test_get_exp_branch.rs
- nimbus/tests/test_updates.rs
I think this is roughly what will need to happen once uniffi allows us to opt-out of it managing locking
> Make NimbusClient Send+Sync via mutexes and cells

- nimbus/src/dbcache.rs
Today I learned that, since Rust's locking primitives provide mutable references, we don't need constructs like `Mutex<RefCell<T>>` and can instead directly use the lock to provide the mutability.
> Simplify concurrency primitives in `DatabaseCache`.

- nimbus/src/dbcache.rs
- nimbus/src/enrollment.rs
- nimbus/src/lib.rs
- nimbus/src/persistence.rs
- nimbus/src/updating.rs
This commit started out with the observation that the Rkv `Database`
class is `Sync` and `Send`, so we don't need to wrap it in a separate
mutex in order to coordinate use from multiple threads. One less mutex
should be a nice cleanup, right?
Turns out we were depending on that mutex for guarding against stale
updates in the database caching layer, so I've refactored that to make
it depend instead on the caller passing in an explicit write transaction.
In the process of doing *that*, I discovered that the way we manage
database transactions seems pretty haphazard. Some functions take just
a `&Database` and manage their own transaction, while their peers take
both `&Database` and `&mut Writer`. We even had a read-only function
that was taking a `&mut Writer` purely so that it could …
> Refactor DB to remove mutex, use more explicit transactions.

- CHANGELOG.md
- nimbus/Cargo.lock
- nimbus/Cargo.toml
Update the changelog and the version number.
> Release v0.8.0

- nimbus/src/enrollment.rs
- nimbus/src/lib.rs
- nimbus/src/persistence.rs
In #96 we added a new `feature_id` field to `EnrollmentStatus::Enrolled` but did not add a corresponding db migration. Since there may be Nimbus databases in the wild with serialized `EnrollmentStatus` values that are missing this field, let's default it to the empty string, to avoid bricking the db with serde deserialization failures.
@jhugman Sorry I missed this in the review of #101 but stumbled across it while preparing to cut a new release. I've tried to add some more explicit tests and docs to help us avoid similar oversights in future.
(More broadly, it's really unfortunate that a single corrupted item in the store currently means that any call to `collect_all()` for that store will fail, basically bricking the store. We should do better, but that's a bigger change for a separate …
> Fill in a default feature_id for enrollments where it is missing.
