experiments/Cargo.lock, experiments/Cargo.toml, experiments/src/error.rs, experiments/src/evaluator.rs
First pass at adding jexl evaluation.
`jexl-rs` still needs a bit more work before it's ready though.
Marking as a draft until we put `jexl-rs` into crates.io or (decide to just point it to GitHub)
=> First pass at adding jexl-rs

experiments/Cargo.lock, experiments/Cargo.toml, experiments/examples/experiment.rs, experiments/src/config.rs, experiments/src/error.rs, experiments/src/evaluator.rs, experiments/src/http_client.rs, experiments/src/lib.rs, experiments/src/nimbus.idl
This PR allows us to query experiments from [stage](https://settings.stage.mozaws.net/v1/buckets/main/collections/messaging-experiments/records) that abide by the nimbus schema, and omitting experiments that do not abide by the schema (with a minor detail, the `proposedDuration` is missing from ***all*** experiments in stage, so I made it optional (although the schema said it's required) and added a TODO there.
=> Skips invalid experiments recieved from the server

experiments/src/evaluator.rs, experiments/src/http_client.rs, experiments/src/lib.rs
Sync schema changes between [mozilla-central](https://searchfox.org/mozilla-central/rev/84922363f4014eae684aabc4f1d06380066494c5/toolkit/components/messaging-system/experiments/@types/ExperimentManager.d.ts) and nimbus-shared (https://github.com/mozilla/nimbus-shared/pull/119 and https://github.com/mozilla/nimbus-shared/pull/118/)
=> Bug 1656502, 1631658 - Add FeatureConfig and deprecate use of filter_expression

.circleci/config.yml
RustBuffer changes caused a fail in https://app.circleci.com/pipelines/github/mozilla/nimbus-sdk/77/workflows/3c19ee42-9ba9-4ee0-893d-3d39a027d122/jobs/84
=> Rollback uniffi version

.circleci/config.yml
It's important that the version installed here matches the version used in the `Cargo.toml` of the experiments crate.
I think this should fix the issue from https://github.com/mozilla/nimbus-sdk/pull/22, closing https://github.com/mozilla/application-services/issues/3583.
=> Install uniffi from crates.io in CircleCI

android/.buildconfig.yaml, android/build.gradle, android/publish.gradle, android/settings.gradle, android/src/main/AndroidManifest.xml, experiments/Cargo.toml, experiments/examples/experiment.rs
This is a WIP towards getting unit tests to run (in consuming code like the [Nimbus Android-Component](https://github.com/mozilla-mobile/android-components/pull/8261)) and include the local system libs rather than just the android libs.
=> [SYNC-1751] Fix packaging of nimbus to include native libs for unittesting.

nimbus/src/lib.rs
This implements the functionality for get_experiment_branch.  Upon implementing this, I realized that this function was not extremely useful aside from a convenience function since we already return the branch slug as a property of the collection of EnrolledExperiments.
=> Closes [EXP-384] Implement get_experiment_branch

nimbus/src/lib.rs
I forgot to remove the underscore in the `get_experiment_branch` function.
=> Rename `_slug` to `slug` in `get_experiment_branch`

nimbus/examples/experiment.rs, nimbus/src/evaluator.rs, nimbus/src/http_client.rs, nimbus/src/lib.rs
The experiment schema defined over in [nimbus-shared](https://github.com/k88hudson/nimbus-shared/blob/fb9bacac84fedd6c268621add00966775b6c9dd2/types/experiments.ts#L77) has had a few modifications recently, which IMHO make it substantially better for our purposes. I was going through the details and figured I might as well update the rust code to track it while I was in there.
This is WIP only because I don't know whether we need to wait for these schema changes to get deployed to a server somewhere, ref https://jira.mozilla.com/browse/SYNC-1794
=> Update to track latest nimbus schema

nimbus/examples/experiment.rs, nimbus/src/config.rs, nimbus/src/evaluator.rs, nimbus/src/http_client.rs, nimbus/src/lib.rs, nimbus/src/nimbus.idl
Fixes [NIBSSD-66](https://jira.mozilla.com/browse/NIBSSD-66) and [NIBSSD-67](https://jira.mozilla.com/browse/NIBSSD-67).
One of the main pieces of this patch is the introduction of `AvailableRandomizationUnits`, passed by the app at initialization time, which allows experiments to have a custom bucketing strategy.
=> IDs refactor

nimbus/Cargo.lock, nimbus/Cargo.toml, nimbus/examples/config/config.json, nimbus/examples/experiment.rs, nimbus/src/enrollment.rs, nimbus/src/error.rs, nimbus/src/evaluator.rs, nimbus/src/lib.rs, nimbus/src/nimbus.idl, nimbus/src/persistence.rs
Wire up persistence of enrolled experiments.
* experiments and enrollment status are all stored in the DB. Only
fetches experiments in the constructor if there are none in the DB,
which doesn't smell like the right thing long term - otherwise though,
you must explicitly call `update_experiments()`. We should work out
what behaviour makes sense for apps here.
* Fully implements the `opt_out` etc methods. Any experiment can be opted in
to and opted out of, with this stored in the DB. Calling
`update_experiments()` will not change the opted-on/out status - there's
a new 'reset_enrollment` function that does though. Note that opting
out is fully supported, but the expectation is that this must only be
used in a dev or test context.
* When `update_experiments()` is called, enrollments for …
=> A bit of a straw-man for how persistence might work.

nimbus/Cargo.lock, nimbus/Cargo.toml
This bumps jexl-rs version to 0.1.7, which contains @eoger's checkin of the parsers.  That shrinks the number of Nimbus dependencies from 152 to 199, in addition to getting rid of some truly giant files!
=> Modify Cargo.toml and friends to use patched version of jexl

nimbus/examples/experiment.rs, nimbus/src/config.rs, nimbus/src/http_client.rs, nimbus/src/lib.rs, nimbus/src/nimbus.idl
I split this from #38 mainly for ease of review. Note that @rfk and I discussed adding constants for the default server URLs, but given the discussion started by @jhugman it's not clear yet that is actually desirable - string constants in the consuming code are probably less likely to be overlooked than, eg, `Servers.RELEASE`
Explicitly flagging @travis79 for review as it will (somewhat trivially) break his a-c PR.
=> Make RemoteSettingsConfig and the server URL inside it non-optional

nimbus/src/client/fs_client.rs, nimbus/src/client/http_client.rs, nimbus/src/client/mod.rs, nimbus/src/error.rs, nimbus/src/lib.rs, nimbus/src/nimbus.idl, nimbus/tests/experiments/README.md, nimbus/tests/experiments/invalid-experiment-missing-slug.json, nimbus/tests/experiments/secure-gold.json, nimbus/tests/test_fs_client.rs
This PR adds a "file system" client, intended for developers (and later, I suspect it will be used for tests). I ended up splitting the other stuff out into their own PRs.
If the `server_url` is a `file://` URL, the new "file system client" will be used. In this case, we expect the URL to point to a directory, and we will serve up the .json files as experiment. Also includes a directory where we can start to accumulate "useful" experiments and a test.
=> Add a 'file system' client and update the experiment cmdline app

nimbus/examples/config/config.json, nimbus/examples/config/rapid-release-control.json, nimbus/examples/config/rapid-rutabagas-treatment.json, nimbus/examples/experiment.rs, nimbus/src/enrollment.rs, nimbus/src/lib.rs
* Reinstates the `gen-uuid` command, and optionally sets
the discovered uuid in the database. Also shows progress
so you can see if you are in a loop that's likely to never
complete.
* Adds a `brute-force` command which shows how any number of enrollments
actually ends up being distributed.
=> Add some enhancements to the 'experiment' example

nimbus/examples/experiment.rs, nimbus/src/enrollment.rs, nimbus/src/evaluator.rs, nimbus/src/lib.rs, nimbus/src/nimbus.idl, nimbus/tests/test_fs_client.rs
How does this look? I don't think there's anything we can do here to avoid JS code dealing with the dummy field, although I think @travis's a-c PR can hide that from Android app consumers.
(I'm also assuming an `i8` works around the problem and is lighter-weight than a string - @dmose is it your understanding that should work OK?)
=> Make AvailableRandomizationUnits.client_id optional and add a dummy field, reverting #45

.circleci/config.yml, nimbus/Cargo.lock, nimbus/Cargo.toml
Obviously, CI won't pass and I won't try to land this until after the uniffi PR lands.
=> Bump uniffi dependency to 0.4.0 to fix license goofiness for m-c

android/.buildconfig.yaml, nimbus/Cargo.lock, nimbus/Cargo.toml
The rust crate claims to be at v1.0.0 already so I figured I'd make the Kotlin package match, but I'm open to bikeshedding on that front.
=> Release v0.3.0

nimbus/src/lib.rs, nimbus/src/nimbus.idl
Unsigned types are currently experimental in Kotlin, and can only be
used by consumers if they explicitly opt in. Let's not put this opt-in
requirement on all consumers of this SDK if we can avoid it.
=> Use a signed byte for the dummy value in AvailableRandomizationUnits.

nimbus/src/enrollment.rs
This isn't used in the main library but *is* used by examples, so let's silence the warning. (It's causing compile failures for the appservices megazord in taskcluster, where warnings seem to be treated as errors)
=> Ignore spurious dead-code warnings about `is_enrolled`.

CHANGELOG.md, android/.buildconfig.yaml, nimbus/Cargo.toml
Technically a breaking change because of the `u8` -> `i8` thing...
=> Release v0.4.0

nimbus/Cargo.lock, nimbus/Cargo.toml, nimbus/src/persistence.rs
Not sure if we have any particular concerns about this new version, but it's the version that glean is using so it seems worthwhile to try to stay aligned.
We could also consider copying some of the "safe-mode" infrastructure that Glean is using, which IIUC will be required for using this on Desktop. But that can be for a separate PR.
=> Update to rkv v0.15

nimbus/examples/README.md, nimbus/examples/experiment.rs, nimbus/src/client/http_client.rs, nimbus/src/config.rs, nimbus/src/nimbus.idl, nimbus/tests/test_fs_client.rs
The Remote Settings data model consists of buckets that contain
collections that contain records. Currently the `RemoteSettingsConfig`
data class orders its fields as server url, then collection, then
bucket (like some sort of reverse American-format date).
To help readers build an accurate mental model, this commit changes
the field order so they appear in order of increasing specificity
just like they would in the underlying URL: root server URL, then
bucket, then collection (like a nice ISO-8601-format date).
=> Make "bucket" preceed "collection" in `RemoteSettingsConfig`.

nimbus/Cargo.lock, nimbus/Cargo.toml
This makes the crate compatible with Rust v1.43, which is required
for vendoring into application-services.
=> Update to uniffi v0.5.0

nimbus/src/enrollment.rs, nimbus/src/lib.rs, nimbus/src/nimbus.idl
This PR adds a global opt in or opt out for all experiments for the user to express a preference about participating in any experiments.
If the user has opted out, `get_active_experiments()` returns an empty list of experiments.
The naming is a bit clunky, because:
1. This flag codes for "don't enroll  the user in new experiments" as well as "opt out of already enrolled experiments".
2. I'd prefer it to be a positive choice (`!is_enabled` is better than `is_disabled`).
The name `globalUserParticipation` was first proposed in the [Nimbus Android Component API doc][1]
This corresponds to @tdsmith  [Unpacking opting out][3] compatible with [Intent to treat analysis][4].
* If the user is already enrolled in an experiment, then the experiment is given an enrollment status of `OptedOut`.
* When …
=> Add global opt in/out

CHANGELOG.md, android/.buildconfig.yaml, nimbus/Cargo.lock, nimbus/Cargo.toml
This time with updated `Cargo.lock`, which I forgot to do over in https://github.com/mozilla/nimbus-sdk/pull/63
=> Release v0.5.1

CHANGELOG.md, nimbus/src/client/http_client.rs, nimbus/src/enrollment.rs, nimbus/src/error.rs, nimbus/src/evaluator.rs, nimbus/src/lib.rs, nimbus/tests/experiments/invalid-experiment-missing-slug.json, nimbus/tests/experiments/secure-gold.json
This is still a WIP for adding schema version validation.
Design requirements:
* SDK maintains awareness of the supported schema version
* Check the "schemaVersion" field before doing any other processing or validation of experiment config.
* If the major version number is higher than the version supported by the SDK, ignore the experiment (in future we would probably emit some diagnostic telemetry here)
* Document how this is meant to work for clients and their responsibility in testing and updating the nimbus-sdk.
Open question:
* Is backwards compatibility for all previous versions assumed? If not - what are the limits?
=> Add schema version validation

nimbus/examples/experiment.rs, nimbus/src/client/mod.rs, nimbus/src/client/null_client.rs, nimbus/src/lib.rs, nimbus/src/nimbus.idl, nimbus/tests/test_fs_client.rs
Fixes [SDK-97][1].
It makes the remote settings config an `Option` and configures the SDK to use a `NullClient` which serves no experiments.
[1]: https://jira.mozilla.com/browse/SDK-97
=> Make RemoteSettingsConfig nullable in NimbusClient constructor

CHANGELOG.md, nimbus/src/lib.rs, nimbus/src/persistence.rs, nimbus/tests/test_fs_client.rs
(Based on the behaviour @eoger and @travis79 noted in our meeting earlier today).
Previously, we would implicity call `update_experiments` when trying
to list the experiments in an empty database. We would not update
if the database contained at least one experiment, no matter how stale.
In practice this seems to be a bit of a footgun, because it looks
to consumers like we'll automatically update definitions when
initialising the client, but this only works once.
Instead, let's require consumers to make an explicit call to
`update_experiments` whenever they want to update the experiments.
This will require us to do https://jira.mozilla.com/browse/SDK-121 on
the android-components side.
=> Don't implicitly update experiments on first use.

CHANGELOG.md, nimbus/examples/experiment.rs, nimbus/src/client/http_client.rs, nimbus/src/enrollment.rs, nimbus/src/error.rs, nimbus/src/evaluator.rs, nimbus/src/lib.rs, nimbus/src/nimbus.idl, nimbus/src/persistence.rs
Fixes [SDK-122](https://jira.mozilla.com/browse/SDK-122)
This is quite a big patch, it implements the different enrolment state and transitions seen in [this document](https://docs.google.com/document/d/18L3oNriwwLd5TZrM1SaHIfIJXmXqUkwNwQEPwVOTY6Q/edit).
=> Refactor enrollments and return events

nimbus/Cargo.lock
This resolves the `cargo audit` issue noted in https://jira.mozilla.com/browse/SDK-144, as well as updating various other things to newer versions. For reference, all I did here was run `cargo update`, run the tests, and commit the result.
=> Run `cargo update`.

nimbus/src/enrollment.rs, nimbus/src/lib.rs, nimbus/src/persistence.rs
The root cause of the [SDK-149](https://jira.mozilla.com/browse/SDK-149) was that we were trying to deserialize variants that did not exist anymore. I think for this specific migration it is okay to throw everything away and re-populate the database, however for the future db upgrades we will have to do proper migrations.
=> Implement DB upgrade mechanism

nimbus/examples/experiment.rs, nimbus/src/client/fs_client.rs, nimbus/src/client/http_client.rs, nimbus/src/client/mod.rs, nimbus/src/client/null_client.rs, nimbus/src/error.rs, nimbus/src/lib.rs, nimbus/src/nimbus.idl, nimbus/tests/test_fs_client.rs
Fixes [SDK-15](https://jira.mozilla.com/browse/SDK-15).
I based my implementation on the [Kinto docs](https://docs.kinto-storage.org/en/latest/api/1.x/backoff.html?highlight=retry), the code itself is a spin-off of what we do in the a-s fxa-client.
=> Implement Backoff/Retry-After support

.circleci/config.yml, nimbus/Cargo.lock, nimbus/examples/experiment.rs
This will help guard against downstream integration problems
when shipping via appservices.
I've also included a `cargo update`, which will help with https://github.com/mozilla/application-services/pull/3770
=> Lint with clippy like appservices does.

nimbus/src/evaluator.rs
Is this worth a fix? Came across the issue when trying to generate uuids (for the demo) to match the correct branches.
=> Input to choose_branch should not include a dash

nimbus/src/enrollment.rs, nimbus/src/lib.rs, nimbus/src/nimbus.idl
In order to have access to the enrollment_id for the purpose of emitting the exposure event from the Android-Component layer, we need to add it to the EnrolledExperiment struct as a string, which already gets passed across the FFI and is available through the get_active_experiments() function.
=> Add enrollment_id to the `EnrolledExperiment` struct

CHANGELOG.md, nimbus/examples/experiment.rs, nimbus/src/client/fs_client.rs, nimbus/src/client/http_client.rs, nimbus/src/client/mod.rs, nimbus/src/client/null_client.rs, nimbus/src/error.rs, nimbus/src/lib.rs, nimbus/src/nimbus.idl, nimbus/src/persistence.rs, nimbus/src/sampling.rs, nimbus/src/updating.rs, nimbus/tests/test_fs_client.rs, nimbus/tests/test_updates.rs
This PR addresses [SDK-142][1].
We split the `update_experiments` method in two to give the [app more control][2] over when experiment changes happen.
Two methods (`set_experiments_locally` and `fetch_experiments`) stash the experiments in a new rkv table called `Updates`.
This table is managed by the methods in `updating.rs`, which provides methods `stash` and a `pop` the updates.
The function `apply_pending_updates` is largely the same as `update_experiments`, but gets its `Experiment`s from the stashed updates. 
`Client::get_experiments` and `http_client::Client::get_experiments` has changed to as to re-use the fault-tolerant deserialization of experiments for both `http_client` and from the new `set_experiments_locally`.
[1]: https://jira.mozilla.com/browse/SDK-142
[2]: …
=> Split update_experiments into two phases

.gitignore, nimbus/examples/config/config.json, nimbus/examples/experiment.rs, nimbus/src/lib.rs
This fixes the experiment CLI example, specifically the `gen-uuid` and `brute-force` commands which didn't quite work after the updates to the `EnrollmentStatus` which added the `enrollment_id`.
=> [SDK-159] Fix experiment example

nimbus/src/client/http_client.rs, nimbus/src/persistence.rs
There are 2 RKV errors that seem to indicate a clearly invalid DB (and [SDK-163](https://jira.mozilla.com/browse/SDK-163) hits one of them.) On these errors we delete the entire `db` directory then recreate it and recreate the DB. This seems a little scary, but the only other alternative is to have a set of files we know to delete, but that seems fragile - there might be other rkv files that only exist in edge-cases (or in future versions) and leaving them behind might cause further problems.
There's a bonus commit which adds an experiment without a schema-version to some tests, but as expected, this is handled correctly. I didn't think it was worth its own PR, but also didn't want to discard it.
=> Delete the database if opening it fails with an error indicating it is invalid or corrupt

CHANGELOG.md, nimbus/src/enrollment.rs, nimbus/src/lib.rs, nimbus/src/nimbus.idl
Fixes [SDK-136](https://jira.mozilla.com/browse/SDK-136).
When the user disables telemetry in the consuming application, we need
to reset any unique identifiers used internally by the SDK. This guards
against accidentally correlating metrics submitted before the opt-out
with metrics that the user may opt-in to submitting again in future.
Consumers are expected to call `on_telemetry_disabled` when the user
disables telemetry in order to trigger resetting of the identifiers.
This needs tests before it's ready for review, but I wanted to push it early for feedback in light of https://github.com/mozilla/nimbus-sdk/pull/78. IIUC, the work in https://github.com/mozilla/nimbus-sdk/pull/78 is based on the notion that we should not change experiment enrollment state as an incidental side-effect of …
=> Add `reset_telemetry_identifiers` method

CHANGELOG.md, nimbus/src/enrollment.rs, nimbus/src/lib.rs, nimbus/src/nimbus.idl
Fixes https://jira.mozilla.com/browse/SDK-136. This is a continuation of #80 which got backed out for conflicting with the threadsafe work. I'll highlight the things that have changed related to #80 in comments below.
---
When the user disables telemetry in the consuming application, we need
to reset any unique identifiers used internally by the SDK. This guards
against accidentally correlating metrics submitted before the opt-out
with metrics that the user may opt-in to submitting again in future.
Consumers are expected to call `reset_telemetry_identifiers` when the user
disables telemetry in order to trigger resetting of the identifiers.
They may also call it when the user re-enables telemetry in order to
provide updated randomization unit values.
=> Add `reset_telemetry_identifiers` method.

CHANGELOG.md, nimbus/Cargo.lock, nimbus/Cargo.toml
This release makes the new `reset_telemetry_identifiers` method available to considers.
This seems to want to merge the release commits from previous `v0.7.x` releases into main as well, although the changelog entries etc are already there. I guess maybe we did a rebase-merge to get them onto `main` rather than creating a merge commit? Anyway, I did a merge commit to try to sync things up.
=> Merge v0.7.2 to main

nimbus/src/enrollment.rs, nimbus/src/evaluator.rs, nimbus/src/lib.rs, nimbus/tests/common/mod.rs, nimbus/tests/test_get_experiment_branch_by_feature.rs, nimbus/tests/test_get_experiment_branch_by_id.rs, nimbus/tests/test_updates.rs
This PR replaces #100, and fixes SDK-190.
Not long ago, experimenter was producing experiment JSON without an array for `feature_ids`.
Unfortunately, some of these experiments are still live. The experiments were not being parsed,
and mass enrollments happened.
Going forward, `feature_ids` should be a required field.
This PR defaults `feature_ids` when missing to an empty vec of strings. For parts of the code that require a `featue_id`, an empty string is used. This will need to be revisited once we actually support multiple features per branch.
=> Add test to prove experiments without a feature_ids field work

nimbus/Cargo.lock
This silences a `cargo audit` warning that doesn't matter to us in
practice, but is still nice to avoid.
Fixes https://jira.mozilla.com/browse/SDK-201
=> Update hyper to latest version.

CHANGELOG.md, nimbus/Cargo.lock, nimbus/Cargo.toml
As prescribed by [release process][1].
[1]: https://github.com/mozilla/nimbus-sdk/blob/main/README.md#cutting-a-release
=> Release v0.8.1

nimbus/Cargo.lock, nimbus/Cargo.toml, nimbus/src/error.rs
We were debating whether to upgrade rkv before the next release and I'm leaning towards that we should for the following reasons:
* [glean is on it](https://github.com/mozilla/glean/commit/4a3443f594) as is [mozilla-central is on it](https://searchfox.org/mozilla-central/rev/5120ec68572d946bd15101cf2ee2eaf4a210724f/Cargo.lock#4358) and both have been for weeks now.
* It removes a dependency - rkv now uses `thiserror` which is the same error package we use. This also means we can remove some boilerplate in our error.rs
=> Update rkv to 0.17.0

CHANGELOG.md, nimbus/Cargo.toml
This is mostly to make the changes from #106 available for use in appservices.
=> Release v0.8.2

CHANGELOG.md, nimbus/Cargo.toml
As per description, in service of https://github.com/mozilla/application-services/pull/3901 .
=> Upgrade uniffi to 0.8.0, for iOS

CHANGELOG.md, nimbus/src/client/http_client.rs, nimbus/src/client/mod.rs, nimbus/src/dbcache.rs, nimbus/src/enrollment.rs, nimbus/src/error.rs, nimbus/src/evaluator.rs, nimbus/src/lib.rs, nimbus/src/nimbus.udl, nimbus/src/persistence.rs, nimbus/src/sampling.rs, nimbus/tests/test_get_experiment_branch_by_feature.rs, nimbus/tests/test_get_experiment_branch_by_id.rs
This PR prevents collisions between `Error` (from Nimbus) and `Error` from Swift.
The Swift `Error` isn't namespaced, so when compiling the generated swift file, the Nimbus Error is mistaken for the Swift one.
This is split into two implementations: the first commit is the minimally invasive change, using import aliasing.
The second does the actual rename. Reviewers are invited to tell me if I should drop the second commit or not.
=> Rename Error to NimbusError
